"""PyPWCT - Programming Without Coding Technology (Python edition).

A Python/Tkinter re-implementation of PWCT 1.9 (Art) by Mahmoud Samir Fayed.
The visual source is a tree of steps generated by interacting with components;
the steps carry Python code that is extracted, indented and executed.
"""

VERSION = "1.3"
APP_NAME = "Programming Without Coding Technology"
APP_TITLE = "PyPWCT %s" % VERSION
FILE_EXT = ".pwct"
